apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir-disk-pod
  namespace: default
spec:
  containers:
  - name: myapp
    image: 121.40.27.163:30002/lyd-demo/mynginx:1.0
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/nginx/logs
      name: logs-volume
  - name: tools-volume
    image: 121.40.27.163:30002/lyd-demo/busybox:1.0
    command: ["/bin/sh", "-c", "touch /logs/access.log && tail -f /logs/access.log"]
    volumeMounts:
    - mountPath: /logs
      name: logs-volume
  volumes:
  - name: logs-volume
    emptyDir: {}

