apiVersion: v1 #接口组
kind: ConfigMap #类别
metadata:
  name: literal-config #cm名字
  namespace: default #命名空间
data: #定义数据
  name: dave
  password: pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO
---
apiVersion: v1 #接口组版本
kind: Pod #类别
metadata:
  name: cm-env-test-pod #pod名字
spec: #期望
  containers:
    - name: test-container
      image: 121.40.27.163:30002/lyd-demo/mynginx:1.0
      command: [ "/bin/sh", "-c", "env"] #当前启动命令
      env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: name
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: password
      envFrom:
        - configMapRef:
            name: env-config
  restartPolicy: Never

