apiVersion: v1
kind: Pod
metadata:
  name: cm-command-pod
spec:
  containers:
    - name: myapp-container
      image: 121.40.27.163:30002/lyd-demo/mynginx:1.0
      command: ["/bin/sh","-c","echo ${USERNAME}${PASSWORD}"]
      env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: name
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: literal-config
              key: password
  restartPolicy: Never     
