apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nodeport-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      release: stabel
      svc: nodeport
  template:
    metadata:
      labels:
        app: myapp
        release: stabel
        env: test
        svc: nodeport
    spec:
      containers:
      - name: myapp-container
        image: 121.40.27.163:30002/lyd-demo/mynginx:1.0
        ports:
        - name: http
          containerPort: 80
